name: kurban_open_im
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  cupertino_icons: ^1.0.8
  flutter_openim_sdk: ^3.8.3+hotfix.10.1
  json_serializable: ^6.11.3
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  rxdart_flutter: ^0.0.2
  connectivity_plus: ^7.0.0
  pinput: ^6.0.0
  pull_down_button: ^0.10.2
  string_validator: ^1.2.0
  scrollview_observer: ^1.26.2
  chat_bottom_container: ^0.4.0
  flex_color_scheme: ^8.3.1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  permission_handler: ^12.0.1
  animate_do: ^4.2.0
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.7
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  azlistview: ^2.0.0
  dio: ^5.9.0
  crypto: ^3.0.7
  lpinyin: ^2.0.3
  intl: any
  video_player: ^2.10.1
  image_picker: ^1.2.1
  mime: ^2.0.0
  flutter_slidable: ^4.0.3
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/emojis/